#!/bin/bash
set -e

APP_NAME="MRR Bar"
BUNDLE_ID="com.mrrbar.app"
VERSION="1.0"
APP_DIR="$APP_NAME.app"

# Replace with your appcast URL before shipping
APPCAST_URL="https://kaiofreitas.github.io/mrr-bar/appcast.xml"
# Public key generated by generate_keys (already done — do not regenerate)
PUBLIC_ED_KEY="oi1mv2UTwdwSMtrncxzp7tqq9ypJ5yZBNWDCpbbjYEY="

echo "Building..."
swift build -c release

# Detect build arch directory
ARCH_BUILD=$(ls .build | grep "apple-macosx" | grep -v "checkouts\|artifacts\|manifest" | head -1)
BUILD_DIR=".build/$ARCH_BUILD/release"

echo "Creating .app bundle..."
rm -rf "$APP_DIR"
mkdir -p "$APP_DIR/Contents/MacOS"
mkdir -p "$APP_DIR/Contents/Frameworks"
mkdir -p "$APP_DIR/Contents/Resources"

cp "$BUILD_DIR/MRRBar" "$APP_DIR/Contents/MacOS/MRRBar"

# Embed Sparkle.framework
cp -R "$BUILD_DIR/Sparkle.framework" "$APP_DIR/Contents/Frameworks/"

# Fix rpath so the binary finds Sparkle at runtime
install_name_tool -add_rpath "@executable_path/../Frameworks" "$APP_DIR/Contents/MacOS/MRRBar" 2>/dev/null || true

cat > "$APP_DIR/Contents/Info.plist" << EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleExecutable</key>
    <string>MRRBar</string>
    <key>CFBundleIdentifier</key>
    <string>$BUNDLE_ID</string>
    <key>CFBundleName</key>
    <string>$APP_NAME</string>
    <key>CFBundleDisplayName</key>
    <string>$APP_NAME</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleShortVersionString</key>
    <string>$VERSION</string>
    <key>CFBundleVersion</key>
    <string>$VERSION</string>
    <key>LSMinimumSystemVersion</key>
    <string>13.0</string>
    <key>NSPrincipalClass</key>
    <string>NSApplication</string>
    <key>LSUIElement</key>
    <true/>
    <key>NSHighResolutionCapable</key>
    <true/>
    <key>SUFeedURL</key>
    <string>$APPCAST_URL</string>
    <key>SUPublicEDKey</key>
    <string>$PUBLIC_ED_KEY</string>
    <key>SUEnableAutomaticChecks</key>
    <true/>
</dict>
</plist>
EOF

echo ""
echo "Done! '$APP_DIR' is ready."
echo "Drag it to /Applications to install."
